version: '3'

services:

  app:
    build: ./docker/php
    container_name: app-srp-ocp
    restart: always
    environment:
      - XDEBUG_CONFIG=client_host=192.168.10.7 client_port=9003 start_with_request=yes log=/var/log/xdebug.log
      - XDEBUG_MODE=debug
      - XDEBUG_SESSION=phpstorm
      - PHP_IDE_CONFIG=serverName=docker-server
    #      O server-docker é uma configuração em PHP -> Server em que você colocará e host=localhost porta=8000 e o path mappings pegando a raiz do projeto e apontando pra /var/www
    volumes:
      - ./:/var/www
    expose:
      - 9002
    networks:
      - srp_ocp_network
    depends_on:
      - db

  nginx:
    build: ./docker/nginx
    container_name: nginx-srp-ocp
    restart: always
    tty: true
    ports:
      - "81:80"
    volumes:
      - ./:/var/www
    networks:
      - srp_ocp_network
    depends_on:
      - app
  db:
    build: ./docker/mysql
    container_name: mysql-srp-ocp
    restart: always
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./db-volumes:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=srp_ocp_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - srp_ocp_network

networks:
  srp_ocp_network:
    driver: bridge